import type { Metadata } from "next";
import { Merriweather_Sans, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const sourceSans = Source_Serif_4({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sourceSans',
})

const merriweather = Merriweather_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-merriweather',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSans.variable} ${merriweather.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
